export { Nav } from './Nav'
export { Hero } from './Hero'
export { Features } from './Features'
export { HowItWorks } from './HowItWorks'
export { CTA } from './CTA'
export { Footer } from './Footer'
